# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    key            = "{path_relative_to_include()}/terraform.tfstate"
    region         = "us-east-1"
    bucket         = "smmaws-dev-terraform-state"
    dynamodb_table = "smmaws-dev-terraform-locks"
    encrypt        = true
  }
}
